apiVersion: v1
kind: PersistentVolume
metadata:
  name: triton-models-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-010c84cb1be15cfd2:/models
