global:
  resolve_timeout: 5m
route:
  receiver: "slack"
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 3h
receivers:
  - name: "slack"
    slack_configs:
      - api_url: "{{SLACK_WEBHOOK_URL}}" #<--CI should create the alertmanager
        channel: "#mlops-alerts"
        send_resolved: true
