# Provides HTTP (8000), gRPC (8001), metrics (8002).

apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton.fullname" . }}
  labels:
    app: {{ include "triton.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: {{ .Values.ports.grpc }}
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
  selector:
    app: {{ include "triton.name" . }}
