---
name: Terraform Infra Provision

on:
  workflow_run:
    workflows: ["Build & Push Triton Image"]
    types: [completed]

permissions:
  id-token: write       # Required for OIDC
  contents: read

jobs:
  terraform:
    name: Terraform Apply for EKS GPU Platform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      # -----------------------------------------------------
      # 1. Checkout
      # -----------------------------------------------------
      - name: Checkout Repo
        uses: actions/checkout@v4

      # -----------------------------------------------------
      # 2. Configure AWS Credentials (OIDC)
      # -----------------------------------------------------
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/triton-mlops-github-actions-oidc-role
          # role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE }}
          # role-session-name: GitHubActionsOIDCSession
          aws-region: us-east-1

      # -----------------------------------------------------
      # 3. Install Terraform
      # -----------------------------------------------------
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # -----------------------------------------------------
      # 4. Terraform Init
      # -----------------------------------------------------
      - name: Terraform Init
        run: terraform init

      # -----------------------------------------------------
      # 5. Terraform Validate
      # -----------------------------------------------------
      - name: Terraform Validate
        run: terraform validate

      # -----------------------------------------------------
      # 6. Terraform Plan
      # -----------------------------------------------------
      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      # -----------------------------------------------------
      # 7. Terraform Apply (only if previous workflow succeeded)
      # -----------------------------------------------------
      - name: Terraform Apply
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: terraform apply -auto-approve tfplan
